import 'package:flutter/material.dart';

/// Maps backend icon slugs (lucide-style) to Material icons.
IconData categoryIcon(String? slug) {
  switch (slug) {
    case 'wallet':
      return Icons.account_balance_wallet_rounded;
    case 'laptop':
      return Icons.laptop_mac_rounded;
    case 'briefcase':
      return Icons.work_outline_rounded;
    case 'gift':
      return Icons.card_giftcard_rounded;
    case 'trending-up':
      return Icons.trending_up_rounded;
    case 'rotate-ccw':
      return Icons.replay_rounded;
    case 'home':
      return Icons.home_rounded;
    case 'utensils':
      return Icons.restaurant_rounded;
    case 'car':
      return Icons.directions_car_rounded;
    case 'shopping-bag':
      return Icons.shopping_bag_rounded;
    case 'wifi':
      return Icons.wifi_rounded;
    case 'zap':
      return Icons.bolt_rounded;
    case 'film':
      return Icons.movie_rounded;
    case 'book-open':
      return Icons.menu_book_rounded;
    case 'heart-pulse':
      return Icons.favorite_rounded;
    case 'plane':
      return Icons.flight_rounded;
    case 'users':
      return Icons.people_rounded;
    // --- extended set ---
    case 'coffee':
      return Icons.local_cafe_rounded;
    case 'shopping-cart':
      return Icons.shopping_cart_rounded;
    case 'bus':
      return Icons.directions_bus_rounded;
    case 'fuel':
      return Icons.local_gas_station_rounded;
    case 'phone':
      return Icons.smartphone_rounded;
    case 'droplet':
      return Icons.water_drop_rounded;
    case 'dumbbell':
      return Icons.fitness_center_rounded;
    case 'graduation-cap':
      return Icons.school_rounded;
    case 'baby':
      return Icons.child_friendly_rounded;
    case 'paw':
      return Icons.pets_rounded;
    case 'scissors':
      return Icons.content_cut_rounded;
    case 'shirt':
      return Icons.checkroom_rounded;
    case 'music':
      return Icons.music_note_rounded;
    case 'gamepad':
      return Icons.sports_esports_rounded;
    case 'tv':
      return Icons.tv_rounded;
    case 'pill':
      return Icons.medication_rounded;
    case 'stethoscope':
      return Icons.medical_services_rounded;
    case 'building':
      return Icons.apartment_rounded;
    case 'tools':
      return Icons.handyman_rounded;
    case 'shield':
      return Icons.shield_rounded;
    case 'bank':
      return Icons.account_balance_rounded;
    case 'credit-card':
      return Icons.credit_card_rounded;
    case 'piggy-bank':
      return Icons.savings_rounded;
    case 'chart-pie':
      return Icons.pie_chart_rounded;
    case 'coins':
      return Icons.monetization_on_rounded;
    case 'percent':
      return Icons.percent_rounded;
    case 'church':
      return Icons.volunteer_activism_rounded;
    case 'ticket':
      return Icons.confirmation_number_rounded;
    case 'camera':
      return Icons.photo_camera_rounded;
    case 'bike':
      return Icons.pedal_bike_rounded;
    case 'train':
      return Icons.train_rounded;
    case 'sun':
      return Icons.wb_sunny_rounded;
    case 'leaf':
      return Icons.eco_rounded;
    case 'star':
      return Icons.star_rounded;
    case 'hand-heart':
      return Icons.volunteer_activism_rounded;
    case 'receipt':
      return Icons.receipt_long_rounded;
    default:
      return Icons.circle_outlined;
  }
}
